"""
Generate OpenAPI schema from Pydantic models for structured output.

This script generates a JSON Schema/OpenAPI schema that can be used with
AI models that support structured output (e.g., OpenAI function calling,
Anthropic structured outputs, etc.).
"""

from __future__ import annotations

import json
from pathlib import Path

from pianist.schema import Composition


def generate_openapi_schema() -> dict:
    """
    Generate an OpenAPI schema object from the Composition Pydantic model.
    
    Returns a dictionary containing the OpenAPI schema that can be used
    with AI models supporting structured output.
    """
    # Generate JSON Schema from Pydantic model
    # Using mode="serialization" to get the schema as it would be serialized
    json_schema = Composition.model_json_schema(
        mode="serialization",
        by_alias=False,  # Use field names as defined in the model
    )
    
    # Create OpenAPI schema object
    # For structured output, we typically need just the schema definition
    # wrapped in an OpenAPI format
    openapi_schema = {
        "openapi": "3.1.0",
        "info": {
            "title": "Pianist Composition Schema",
            "description": "Schema for piano composition specifications generated by AI models",
            "version": "1.0.0",
        },
        "components": {
            "schemas": {
                "Composition": json_schema,
            },
        },
    }
    
    return openapi_schema


def generate_json_schema_only() -> dict:
    """
    Generate just the JSON Schema (without OpenAPI wrapper).
    
    Some AI models prefer just the JSON Schema directly.
    """
    return Composition.model_json_schema(mode="serialization")


def main() -> None:
    """Generate and save both OpenAPI and JSON Schema formats."""
    # Get the project root (parent of src/)
    project_root = Path(__file__).parent.parent.parent
    
    # Generate schemas
    openapi_schema = generate_openapi_schema()
    json_schema = generate_json_schema_only()
    
    # Save OpenAPI schema
    openapi_path = project_root / "schema.openapi.json"
    with open(openapi_path, "w") as f:
        json.dump(openapi_schema, f, indent=2)
    print(f"Generated OpenAPI schema: {openapi_path}")
    
    # Save JSON Schema
    json_schema_path = project_root / "schema.json"
    with open(json_schema_path, "w") as f:
        json.dump(json_schema, f, indent=2)
    print(f"Generated JSON Schema: {json_schema_path}")
    
    # Also print the JSON Schema for direct use
    print("\n" + "=" * 80)
    print("JSON Schema (for direct use with structured output):")
    print("=" * 80)
    print(json.dumps(json_schema, indent=2))


if __name__ == "__main__":
    main()

